security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory_user_provider:
            memory:
                users:
                    admin:
                        password: '%env(ADMIN_PASSWORD_HASH)%'
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: in_memory_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /dashboard
                always_use_default_target_path: true

            logout:
                path: /logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
