version: "3.9"

services:
    app:
        build: .
        container_name: logeverything-api-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony?serverVersion=8.0.32&charset=utf8mb4"

    web:
        image: nginx:stable
        container_name: logeverything-api-nginx
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: logeverything-api-db
        environment:
            MYSQL_DATABASE: "symfony"
            MYSQL_USER: "symfony"
            MYSQL_PASSWORD: "symfony"
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/db_data:/var/lib/mysql

    rabbitmq:
        image: rabbitmq:3-management
        ports: [ 5672, 15672 ]

volumes:
    db_data:
